version: '2.3'
services:
  master:
    image: srv-builder.fkie.fraunhofer.de:18006/gehring-master-spark:0.0.1-SNAPSHOT
    build: .
    ports:
    - 2000:7077  # Submit job to cluster / Join cluster
    - 2001:8080  # WebUI
    - 2002:5000  # Schedule Executors
    - 2003:5001  # Cluster Manager Executor
    - 2004:5002  # Cluster Manager Driver
    - 2005:4040  # Cluster Manager WebUI
    - 2006:18080 # Cluster Manager History Server
    command: ["/start-master.sh"]
    volumes:
    - "${SUP_LOG_FILES:-/home/simon.gehring/master-logs/}master:/spark/logs"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 2
  slave-one:
    image: srv-builder.fkie.fraunhofer.de:18006/gehring-master-spark:0.0.1-SNAPSHOT
    build: .
    #ports:
    #- 8003:8080
    command: ["/start-slave.sh", "--memory", "${MEMORY_OF_SLAVE_MASTER:-12}G", "--cores", "${CORES_OF_SLAVE_MASTER:-1}", "spark://master:7077"]
    volumes:
    - "${SUP_LOG_FILES:-~/logs/}slave-one:/spark/logs"
    - "${SUP_LOG_FILES:-~/logs/}slave-one/workspace:/spark/work"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 2
  slave-two:
    image: srv-builder.fkie.fraunhofer.de:18006/gehring-master-spark:0.0.1-SNAPSHOT
    build: .
    #ports:
    #- 8004:8080
    command: ["/start-slave.sh", "--memory", "${MEMORY_PER_MACHINE_IN_GB}G", "--cores", "${CORES_PER_MACHINE}", "spark://master:7077"]
    volumes:
    - "${SUP_LOG_FILES:-~/logs/}slave-two:/spark/logs"
    - "${SUP_LOG_FILES:-~/logs/}slave-two/workspace:/spark/work"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 2
  submitter:
    image: srv-builder.fkie.fraunhofer.de:18006/gehring-master-spark:0.0.1-SNAPSHOT
    build: .
    command:
    - "spark-submit"
    - "-v"
    - "--master"
    - "spark://master:6066"
    - "--driver-memory"
    - "12G"
    - "--deploy-mode"
    - "client"
    - "--class"
    - "gehring.uima.examples.ExamplePipelineProcessor"
    - "http://jar-provider/shared-uima-benchmark-0.0.1-SNAPSHOT.jar"
    - "-c"
    - "${SUP_COMPRESSION_ALGORITHM:-gehring.uima.distributed.compression.NoCompression}"
    - "-s"
    - "${SUP_SERIALIZER:-gehring.uima.distributed.serialization.XmiCasSerialization}"
    - "-d"
    - "${SUP_GUTENBERG_RATIO:-1.0}"
    - "${SUP_SINGLE_INSTANCE}"
    - "--minSize"
    - "${FILESIZE_MIN:-0}"
    - "--maxSize"
    - "${FILESIZE_MAX:--1}"
    - "--pipelineId"
    - "${SUP_PIPELINE_ID:-0}"
    - "${SUP_SKIP_COLLECTION:-}"
    volumes:
    - "${SUP_LOG_FILES:-~/logs/}submitter:/spark/logs"
    ports:
    - 8005:4040
    depends_on:
      master:
        condition: service_healthy
      jar-provider:
        condition: service_healthy
  jar-provider:
    image: httpd:alpine
    ports:
    - 8006:80
    volumes:
    - "$PWD/jars:/usr/local/apache2/htdocs"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "-O", "-", "-T", "1", "localhost"]
  document-provider:
    image: httpd:alpine
    ports:
    - 8007:80
    volumes:
    - "$DOCUMENT_DIR:/usr/local/apache2/htdocs"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "-O", "-", "-T", "1", "localhost"]
