version: '2.3'
services:
  master:
    image: srv-builder.fkie.fraunhofer.de:18006/gehring-master-spark:0.0.1-SNAPSHOT
    build: .
    ports:
    - 2000:7077  # Submit job to cluster / Join cluster
    - 2001:8080  # WebUI
    - 2002:5000  # Schedule Executors
    - 2003:5001  # Cluster Manager Executor
    - 2004:5002  # Cluster Manager Driver
    - 2005:4040  # Cluster Manager WebUI
    - 2006:18080 # Cluster Manager History Server
    command: ["/start-master.sh"]
    volumes:
    - "$PWD/logs/master:/spark/logs"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 2
  slave-one:
    image: srv-builder.fkie.fraunhofer.de:18006/gehring-master-spark:0.0.1-SNAPSHOT
    build: .
    ports:
    - 8003:8080
    command: ["/start-slave.sh", "--memory", "2G", "--cores", "2", "spark://master:7077"]
    volumes:
    - "$PWD/logs/slave-one:/spark/logs"
    - "$PWD/logs/slave-one/workspace:/spark/work"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 2
  slave-two:
    image: srv-builder.fkie.fraunhofer.de:18006/gehring-master-spark:0.0.1-SNAPSHOT
    build: .
    ports:
    - 8004:8080
    command: ["/start-slave.sh", "--memory", "6G", "--cores", "4", "spark://master:7077"]
    volumes:
    - "$PWD/logs/slave-two:/spark/logs"
    - "$PWD/logs/slave-two/workspace:/spark/work"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 2
  submitter:
    image: srv-builder.fkie.fraunhofer.de:18006/gehring-master-spark:0.0.1-SNAPSHOT
    build: .
    command: ["spark-submit", "-v", "--master", "spark://master:6066", "--driver-memory", "2G", "--deploy-mode", "cluster", "--class", "sparktest.example.ExamplePipelineProcessor", "http://jar-provider/sparktest-0.0.1-SNAPSHOT.jar", "100"]
    ports:
    - 8005:4040
    depends_on:
      master:
        condition: service_healthy
      jar-provider:
        condition: service_healthy
  jar-provider:
    image: httpd:alpine
    ports:
    - 8006:80
    volumes:
    - "$PWD/jars:/usr/local/apache2/htdocs"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "-O", "-", "-T", "1", "localhost"]
  document-provider:
    image: httpd:alpine
    ports:
    - 8007:80
    volumes:
    - "$PWD/documents:/usr/local/apache2/htdocs"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "-O", "-", "-T", "1", "localhost"]
  log-catcher:
    image: srv-builder.fkie.fraunhofer.de:18006/gehring-log-catcher:0.0.1-SNAPSHOT
    build: ./log-catcher
    volumes:
    - "$PWD/logs/log-catcher:/var/log-catcher/logs"
    